    const items = [
        { name: "Botella vacía", cost: 5, requiredLevel: 0 },
        { name: "Cajita de cartón", cost: 8, requiredLevel: 0 },
        { name: "Libro antiguo", cost: 10, requiredLevel: 0 },
        { name: "Lata de refresco", cost: 12, requiredLevel: 0 },
        { name: "Cuerda de saltar", cost: 20, requiredLevel: 0 },
        { name: "Pelota de goma", cost: 25, requiredLevel: 0 },
        { name: "Juguete roto", cost: 15, requiredLevel: 0 },
        { name: "Revista vieja", cost: 18, requiredLevel: 0 },
        { name: "Bolígrafo usado", cost: 10, requiredLevel: 0 },
        { name: "Caja de fósforos", cost: 5, requiredLevel: 0 },
        { name: "Papel reciclado", cost: 7, requiredLevel: 0 },
        { name: "Taza de cerámica", cost: 12, requiredLevel: 0 },
        { name: "Plato de plástico", cost: 10, requiredLevel: 0 },
        { name: "Cuchara de madera", cost: 8, requiredLevel: 0 },
        { name: "Llavero viejo", cost: 6, requiredLevel: 0 },
        { name: "Cinta adhesiva", cost: 9, requiredLevel: 0 },
        { name: "Piedra decorativa", cost: 11, requiredLevel: 0 },
        { name: "Papel de regalo", cost: 7, requiredLevel: 0 },
        { name: "Marcador seco", cost: 6, requiredLevel: 0 },
        { name: "Cuerda de cáñamo", cost: 10, requiredLevel: 0 },
        { name: "Camiseta básica", cost: 30, requiredLevel: 1 },
        { name: "Sombrero de paja", cost: 35, requiredLevel: 1 },
        { name: "Linterna pequeña", cost: 60, requiredLevel: 1 },
        { name: "Botella de agua", cost: 15, requiredLevel: 1 },
        { name: "Ropa usada", cost: 50, requiredLevel: 1 },
        { name: "Cinturón de tela", cost: 40, requiredLevel: 1 },
        { name: "Bolsa de tela", cost: 25, requiredLevel: 1 },
        { name: "Paraguas pequeño", cost: 55, requiredLevel: 1 },
        { name: "Gorra deportiva", cost: 45, requiredLevel: 1 },
        { name: "Cuaderno nuevo", cost: 20, requiredLevel: 1 },
        { name: "Cartera de mano", cost: 30, requiredLevel: 1 },
        { name: "Calcetines térmicos", cost: 35, requiredLevel: 1 },
        { name: "Guantes de lana", cost: 40, requiredLevel: 1 },
        { name: "Bufanda tejida", cost: 50, requiredLevel: 1 },
        { name: "Cojín pequeño", cost: 45, requiredLevel: 1 },
        { name: "Taza térmica", cost: 55, requiredLevel: 1 },
        { name: "Cargador de pared", cost: 60, requiredLevel: 1 },
        { name: "Bolígrafo de lujo", cost: 50, requiredLevel: 1 },
        { name: "Camiseta estampada", cost: 45, requiredLevel: 1 },
        { name: "Teléfono roto", cost: 400, requiredLevel: 2 },
        { name: "Reloj roto", cost: 100, requiredLevel: 2 },
        { name: "Cámara desechable", cost: 300, requiredLevel: 2 },
        { name: "Radio portátil", cost: 500, requiredLevel: 2 },
        { name: "Cargador portátil", cost: 350, requiredLevel: 2 },
        { name: "Lámpara de escritorio", cost: 200, requiredLevel: 2 },
        { name: "Auriculares básicos", cost: 250, requiredLevel: 2 },
        { name: "Bolso pequeño", cost: 400, requiredLevel: 2 },
        { name: "Reloj digital", cost: 450, requiredLevel: 2 },
        { name: "Cámara compacta", cost: 300, requiredLevel: 2 },
        { name: "Altavoz portátil", cost: 350, requiredLevel: 2 },
        { name: "Teclado básico", cost: 200, requiredLevel: 2 },
        { name: "Mouse óptico", cost: 150, requiredLevel: 2 },
        { name: "Cargador universal", cost: 250, requiredLevel: 2 },
        { name: "Batería externa", cost: 400, requiredLevel: 2 },
        { name: "Lámpara LED", cost: 300, requiredLevel: 2 },
        { name: "Auriculares con cable", cost: 200, requiredLevel: 2 },
        { name: "Bolso de viaje", cost: 450, requiredLevel: 2 },
        { name: "Reloj analógico", cost: 350, requiredLevel: 2 },
        { name: "Bicicleta usada", cost: 800, requiredLevel: 3 },
        { name: "Monopatín usado", cost: 700, requiredLevel: 3 },
        { name: "Mochila resistente", cost: 850, requiredLevel: 3 },
        { name: "Zapatos deportivos", cost: 750, requiredLevel: 3 },
        { name: "Cámara instantánea", cost: 900, requiredLevel: 3 },
        { name: "Cinturón de cuero", cost: 600, requiredLevel: 3 },
        { name: "Reloj de pared", cost: 650, requiredLevel: 3 },
        { name: "Termo de acero", cost: 800, requiredLevel: 3 },
        { name: "Juego de herramientas", cost: 950, requiredLevel: 3 },
        { name: "Cámara de acción", cost: 900, requiredLevel: 3 },
        { name: "Bolso deportivo", cost: 750, requiredLevel: 3 },
        { name: "Zapatos de trekking", cost: 850, requiredLevel: 3 },
        { name: "Cámara de bolsillo", cost: 800, requiredLevel: 3 },
        { name: "Reloj resistente al agua", cost: 700, requiredLevel: 3 },
        { name: "Linterna recargable", cost: 600, requiredLevel: 3 },
        { name: "Auriculares inalámbricos", cost: 950, requiredLevel: 3 },
        { name: "Cargador solar", cost: 900, requiredLevel: 3 },
        { name: "Mochila impermeable", cost: 850, requiredLevel: 3 },
        { name: "Cámara de aventura", cost: 950, requiredLevel: 3 },
        { name: "Pen Drive 32GB", cost: 900, requiredLevel: 4 },
        { name: "Mando de PlaySation 1", cost: 900, requiredLevel: 4 },
        { name: "Auricular Inalambrico", cost: 1200, requiredLevel: 4 },
        { name: "Teclado mecánico", cost: 950, requiredLevel: 4 },
        { name: "Mouse gamer", cost: 1000, requiredLevel: 4 },
        { name: "Cámara web HD", cost: 1100, requiredLevel: 4 },
        { name: "Micrófono USB", cost: 1050, requiredLevel: 4 },
        { name: "Disco duro externo", cost: 1150, requiredLevel: 4 },
        { name: "Altavoces Bluetooth", cost: 1200, requiredLevel: 4 },
        { name: "Cargador rápido", cost: 950, requiredLevel: 4 },
        { name: "Monitor Full HD", cost: 1100, requiredLevel: 4 },
        { name: "Teclado inalámbrico", cost: 1000, requiredLevel: 4 },
        { name: "Mouse ergonómico", cost: 950, requiredLevel: 4 },
        { name: "Cámara de videollamadas", cost: 1200, requiredLevel: 4 },
        { name: "Micrófono de condensador", cost: 1150, requiredLevel: 4 },
        { name: "Auriculares con micrófono", cost: 1050, requiredLevel: 4 },
        { name: "Disco SSD", cost: 1200, requiredLevel: 4 },
        { name: "Cargador inalámbrico", cost: 1100, requiredLevel: 4 },
        { name: "Altavoces de escritorio", cost: 950, requiredLevel: 4 },
        { name: "Buzo Argentina 2010", cost: 1400, requiredLevel: 5 },
        { name: "PC Gamer", cost: 1800, requiredLevel: 5 },
        { name: "Camiseta de fútbol", cost: 1500, requiredLevel: 5 },
        { name: "Tablet usada", cost: 1600, requiredLevel: 5 },
        { name: "Smartwatch básico", cost: 1700, requiredLevel: 5 },
        { name: "Zapatillas de marca", cost: 1550, requiredLevel: 5 },
        { name: "Bolso de cuero", cost: 1450, requiredLevel: 5 },
        { name: "Auriculares premium", cost: 1650, requiredLevel: 5 },
        { name: "Cámara de acción", cost: 1750, requiredLevel: 5 },
        { name: "Reloj inteligente", cost: 1800, requiredLevel: 5 },
        { name: "Cámara compacta avanzada", cost: 1600, requiredLevel: 5 },
        { name: "Zapatos de diseño", cost: 1500, requiredLevel: 5 },
        { name: "Bolso de diseñador", cost: 1700, requiredLevel: 5 },
        { name: "Auriculares de alta fidelidad", cost: 1650, requiredLevel: 5 },
        { name: "Cámara de fotografía", cost: 1750, requiredLevel: 5 },
        { name: "Reloj de lujo", cost: 1800, requiredLevel: 5 },
        { name: "Tablet de gama media", cost: 1600, requiredLevel: 5 },
        { name: "Smartwatch deportivo", cost: 1700, requiredLevel: 5 },
        { name: "Zapatillas exclusivas", cost: 1550, requiredLevel: 5 },
        { name: "Celular usado", cost: 1800, requiredLevel: 6 },
        { name: "Pen Drive 1TB", cost: 2000, requiredLevel: 6 },
        { name: "Laptop usada", cost: 1900, requiredLevel: 6 },
        { name: "Monitor 4K", cost: 2100, requiredLevel: 6 },
        { name: "Consola retro", cost: 2200, requiredLevel: 6 },
        { name: "Cámara de seguridad", cost: 2000, requiredLevel: 6 },
        { name: "Impresora multifunción", cost: 2300, requiredLevel: 6 },
        { name: "Auriculares inalámbricos", cost: 1950, requiredLevel: 6 },
        { name: "Teclado RGB", cost: 1850, requiredLevel: 6 },
        { name: "Silla ergonómica", cost: 2400, requiredLevel: 6 },
        { name: "Monitor de diseño", cost: 2100, requiredLevel: 6 },
        { name: "Consola de videojuegos clásica", cost: 2200, requiredLevel: 6 },
        { name: "Cámara de vigilancia", cost: 2000, requiredLevel: 6 },
        { name: "Impresora láser", cost: 2300, requiredLevel: 6 },
        { name: "Auriculares de estudio", cost: 1950, requiredLevel: 6 },
        { name: "Teclado mecánico avanzado", cost: 1850, requiredLevel: 6 },
        { name: "Silla de oficina", cost: 2400, requiredLevel: 6 },
        { name: "Laptop de diseño", cost: 1900, requiredLevel: 6 },
        { name: "Pen Drive de alta velocidad", cost: 2000, requiredLevel: 6 },
        { name: "Bicicleta nueva", cost: 2500, requiredLevel: 7 },
        { name: "Cámara profesional", cost: 3000, requiredLevel: 7 },
        { name: "Dron básico", cost: 3500, requiredLevel: 7 },
        { name: "Proyector portátil", cost: 2800, requiredLevel: 7 },
        { name: "Smartphone avanzado", cost: 3200, requiredLevel: 7 },
        { name: "Auriculares de estudio", cost: 2700, requiredLevel: 7 },
        { name: "Monitor ultrawide", cost: 3100, requiredLevel: 7 },
        { name: "Consola portátil", cost: 3300, requiredLevel: 7 },
        { name: "Cámara de video", cost: 3400, requiredLevel: 7 },
        { name: "Micrófono profesional", cost: 2900, requiredLevel: 7 },
        { name: "Dron avanzado", cost: 3500, requiredLevel: 7 },
        { name: "Proyector de alta resolución", cost: 2800, requiredLevel: 7 },
        { name: "Smartphone de gama alta", cost: 3200, requiredLevel: 7 },
        { name: "Auriculares de monitoreo", cost: 2700, requiredLevel: 7 },
        { name: "Monitor curvo", cost: 3100, requiredLevel: 7 },
        { name: "Consola de videojuegos portátil", cost: 3300, requiredLevel: 7 },
        { name: "Cámara de grabación", cost: 3400, requiredLevel: 7 },
        { name: "Micrófono de estudio", cost: 2900, requiredLevel: 7 },
        { name: "Bicicleta eléctrica", cost: 2500, requiredLevel: 7 },
        { name: "Cámara de cine", cost: 7000, requiredLevel: 9 },
        { name: "Dron avanzado", cost: 8000, requiredLevel: 9 },
        { name: "Servidor doméstico", cost: 7500, requiredLevel: 9 },
        { name: "Estación de trabajo", cost: 6500, requiredLevel: 9 },
        { name: "Auriculares profesionales", cost: 6200, requiredLevel: 9 },
        { name: "Cámara de alta resolución", cost: 7200, requiredLevel: 9 },
        { name: "Impresora 3D", cost: 7700, requiredLevel: 9 },
        { name: "Monitor 8K", cost: 7800, requiredLevel: 9 },
        { name: "Sistema de realidad virtual", cost: 8100, requiredLevel: 9 },
        { name: "Auto usado", cost: 10000, requiredLevel: 10 },
        { name: "Moto nueva", cost: 12000, requiredLevel: 10 },
        { name: "Yate pequeño", cost: 15000, requiredLevel: 10 },
        { name: "Casa de campo", cost: 20000, requiredLevel: 10 },
        { name: "Avión privado", cost: 50000, requiredLevel: 10 },
        { name: "Helicóptero", cost: 30000, requiredLevel: 10 },
        { name: "Mansión", cost: 60000, requiredLevel: 10 },
        { name: "Isla privada", cost: 100000, requiredLevel: 10 },
        { name: "Submarino personal", cost: 80000, requiredLevel: 10 },
        { name: "Jet privado", cost: 70000, requiredLevel: 10 },
    ];

    items.sort((a, b) => a.cost - b.cost);
    console.log(items);