const lineasData = {
    202: {
        nombre: "202",
        ramales: [
            "[GX1] IDA",
            "[GX1] VUELTA",
            "[P.LARA X ASTILLEROS] DIRECTO",
            "[A PROPULSORA DIRECTO]",
            "[AST-P.LARA] A PTA. LARA X AST",
            "[ASTILLEROS] A ASTILLEROS R.S.",
            "[ASTILLEROS] A BERISSO",
            "[ASTX B.OB.] A AST X B.OBRERO",
            "[ASTXB.OB.] A BSSOX B.OBRERO",
            "[AX60] A LA PLATA",
            "[AX60] A BERISSO",
            "[BX1] A LA PLATA",
            "[BX1] A BERISSO",
            "[CARMEN-BERISSO] A BERISSO",
            "[CARMEN-BERISSO] A EL CARMEN",
            "[CX60] A BERISSO X B.OBRERO",
            "[CX60] A LA PLATA X B.OBRERO",
            "[DX1] A BERISSO (X PORTADA)",
            "[DX1] A BERISSO X B.OBRERO",
            "[DX1] A LA PLATA (X PORTADA)",
            "[DX1] A LA PLATA X B.OBRERO",
            "[ESC10] A ESC. 10 LOS TALAS",
            "[ESC10] DE ESC 10 A MONT.Y 4",
            "[ESC10] ESC 10 A MONT Y 30",
            "[ESC10] HASTA MONTEVIDEO Y 4",
            "[EX60] A BERISSO -BALANDRA",
            "[EX60] A BSSO HASTA ESC.10",
            "[EX60] A BERISSO X UNION",
            "[EX60] A LA PLATA X UNION",
            "[EX60] A LA PLATA X30 XUNION",
            "[FX1] A BERISSO X UNION",
            "[FX1] A LA PLATA X UNION",
            "[G-P.LARA PR] BSSO-L.TALAS DIR",
            "[G-P.TA LARA X AST.] A BERISSO",
            "[G-PTA .LARA] BSSO-L.TALAS DIR",
            "[G-PTA.LARA] BERISSO-LOS TALAS",
            "[GX34] A CEMENTERIO LA PLATA",
            "[GX34] BERISSO LOS TALAS",
            "[G] A BERISSO X122Y52",
            "[G] A CEMENTERIO DE LA PLATA",
            "[G] A CEMENTERIO L.P X122Y52",
            "[G] BERISSO LOS TALAS ESC.",
            "[G] BERISSO LOS TALAS ESC.",
            "[G] BERISSO LOS TALAS X",
            "[H] A BERISSO",
            "[H] A CEMENTERIO DE LA PLATA",
            "[I-AST-BO]P.LARAXAST.XB.O. DIR",
            "[I-PROP] A P.LARA PROP. DIRECT",
            "[I] A PUNTA LARA",
            "[I] A PUNTA LARA DIRECTO",
            "[I] AST-P.LARA DIRECTO",
            "[I] AST-PROP-P.LARA DIRECTO",
            "[J] A NUEVA YORK Y ALSINA",
            "[J] PLAYA BALANDRA",
            "[J] RAMAL BALANDRA",
            "[J] RAMAL BALANDRA",
            "[PROP-PTA.LARA] A P.LARA XPROP",
            "[PTA.LARA-PROP] A BSSO X PROP."
        ]
    },
    214: {
        nombre: "214",
        ramales: [
            "BX64X8 A BERISSO RONDIN",
            "BX64X8 HASTA 121 Y 66 RONDIN",
            "[A] - A 122Y66",
            "[A] A 128Y60 BERISSO",
            "[A] A BERISSO",
            "[A] A FACULTAD 122Y52",
            "[A] A LOS HORNOS DE 122Y66",
            "[A] A LOS HORNOS DE 128Y60",
            "[A] A LOS HORNOS DE FAC 122Y52",
            "[A] HASTA BERISSO X FAC.122Y52",
            "[A] HASTA LOS HORNOS",
            "[A]- A LOS HORNOS X FAC 122Y52",
            "[B155] A BERISSO",
            "[B155] A LOS HORNOS",
            "[BX167X64X8] A BERISSO",
            "[BX167X64X8]-A LOS HORNOS",
            "[BX60X8] - HASTA 8Y145 BERISSO",
            "[BX60X8] A BERISSO",
            "[BX60X8]-A LOS HORNOS",
            "[BX64X8] - HASTA 8Y145 BERISSO",
            "[BX64X8] A BERISSO",
            "[BX64X8]-A LOS HORNOS",
            "[BX64] A BERISSO",
            "[BX64]-A LOS HORNOS HASTA 167",
            "[B] - A 128-60 X64 BERISSO",
            "[B] - A 128Y60 BERISSO",
            "[B] - HASTA 128Y60X64 BERISSO",
            "[B] - HASTA 8Y145 BERISSO",
            "[B] 167 - HASTA 8Y145 BERISSO",
            "[B] A BERISSO",
            "[B] A BERISSO X64",
            "[B] A FACULTAD 122Y52",
            "[B] A FACULTAD 122Y52",
            "[B] A LOS HORNOS",
            "[B] A LOS HORNOS DE 122Y52",
            "[B] A LOS HORNOS DE 128Y60",
            "[B] A LOS HORNOS DE 128Y60 X64",
            "[B] A LOS HORNOS DE FAC 122Y52",
            "[B] A LOS HORNOS DESDE 8 Y 145",
            "[B] A LOS HORNOS X64",
            "[B] DE 167 A BERISSO X64",
            "[B] NOCTURNO HASTA LOS HORNOS",
            "[B]-VUELTA A LOS HORNOS",
            "[D] - HASTA BERISSO",
            "[D] - HASTA LOS HORNOS",
            "[D] A LOS HORNOS DESDE 128Y60"
        ]
    },
    273: {
        nombre: "273",
        ramales: [
            "RINCON DESDE EST. V. ELISA",
            "RINCON DESDE LA GARZA",
            "RONDIN EL RINCON",
            "UNIVERSITARIO IDA",
            "UNIVERSITARIO VUELTA",
            "[5]- A BARRIO SAVOIA",
            "[5]- A P. MORENO",
            "[6] X CENTENARIO A EST.V.ELISA",
            "[6] X CENTENARIO A PZA MORENO",
            "[A1] CEMENT. L.P. A 32 Y 120",
            "[A2] 32 Y 120 A CEMENT. L.P.",
            "[B11] C.BELL X BELG. A CEMENT.",
            "[B11] CEMENT. X BELG. A C BELL",
            "[BC] C.BELL X BELG. A CEMENT.",
            "[BC] CEMENT. X BELG. A C BELL",
            "[BG]CEMENT X BELG. A GUTIERREZ",
            "[BG]GUTIERREZ X BELG.A CEMENT.",
            "[CX 1Y50] X BELG. AL CEMENT.",
            "[CX1Y50] X BELG. A GORINA",
            "[C] CEMENT. POR BELG. A GORINA",
            "[C] GORINA POR BELG. A CEMENT.",
            "[D] A.SEGUI-PZA MORENO X CENT.",
            "[D] HASTA ART. SEGUI",
            "[D] X CENTENARIO A SEGUI",
            "[D] X CENTENARIO AL CEMENT.",
            "[D] X EVE CENT. A P. MORENO",
            "[D] X EVE CENT. A. SGUI",
            "[D] X EVE CENTENARIO AL CEMENT",
            "[F] X CENTENARIO X19 AL CEMENT",
            "[F] X19 X CENTENARIO A GORINA",
            "[G] X 19 X BELGRANO A.SEGUI",
            "[G] X BELGRANO X19 A CEMENT",
            "[G] X BELGRANO X19 A CEMENT",
            "[G] X BELGRANO X19 A SEGUI..",
            "[HX28] CLUB EST. AL CEMENTERIO",
            "[HX28] CLUB.EST. A ARCO.",
            "[HX28] CLUB.EST. A ARCO..",
            "[I AGR.] X LOMAS A LA PLATA",
            "[I-AGRARIA] A LA PLATA",
            "[I-AGRARIA] A RUTA 36",
            "[I-AGRARIA] X LOMAS A RUTA 36",
            "[I] C. LOMAS A CEMENTERIO",
            "[I] HASTA COUNTRY LOMAS IDA",
            "[I] X CENTENARIO A CEMENTERIO",
            "[I] X CENTENARIO A GRAN BELL",
            "[I] X CENTENARIO LOS PORTEÑOS",
            "[TOP] A P. MORENO X CENTENARIO",
            "[TOP] A V. ELISA X CENTENARIO"
        ]
    },
    338: {
        nombre: "338 [TALP]",
        ramales: [
            "30 A VARELA (X RUTA4)",
            "34S.ISIDRO (X RUTA 4 X CAMARG)",
            "A CRZ. LOMAS (X CAMARGO)",
            "A CRZ. LOMAS (X HURLINGAM)",
            "A LA PLATA (X PASCO)",
            "A LA PLATA (X RUTA 4)",
            "A LA PLATA X CENTENARIO",
            "A MORON",
            "A MORON (X B.AYRE X GAONA)",
            "A MORON (X B.AYRE X HURLINGAM)",
            "A MORON (X CAMARGO)",
            "A MORON (X HURLINGAM)",
            "A MORON (X PASCO)",
            "A MORON (X RUTA 4)",
            "A ROT. EL VAPOR",
            "A ROT. EL VAPOR (X CAMARGO)",
            "A ROT. EL VAPOR (X HURLINGAM)",
            "A ROT. S. JUSTO",
            "A ROT.SAN JUSTO (X CAMARGO)",
            "A ROT.SAN JUSTO (X HURLINGAM)",
            "A S. JUSTO(X B.AYRE X HURLING)",
            "A S.ISIDRO (X PASCO X CAMARGO)",
            "A S.ISIDRO (X PASCO X HURLING)",
            "A S.ISIDRO (X RUTA 4 X CAMARG)",
            "A S.JUSTO (X RUTA 4)",
            "A SAN ISIDRO (X CAMARGO)",
            "A SAN ISIDRO (X HURLINGAM)",
            "A SAN JUSTO (X B.AYRE X GAONA)",
            "A SAN JUSTO (X CAMARGO)",
            "A SAN JUSTO (X HURLINGAM)",
            "A SAN JUSTO (X PASCO)",
            "A SAN JUSTO (X RTA 4)",
            "A SAN JUSTO (X RUTA 4)",
            "A TABLADA (HURLINGAM)",
            "A TABLADA (X B.AYRE X GAONA)",
            "A TABLADA (X B.AYRE X HURLING)",
            "A TABLADA (X CAMARGO)",
            "A VARELA (X CENTENARIO)",
            "A VARELA (X PASCO)",
            "A VARELA (X RUTA 4)",
            "ALPARGATAS (X RUTA 4)",
            "ALPARGATAS (X RUTA4)",
            "HASTA PABLO PODESTÁ",
            "HASTA RUTA 8",
            "HASTA SAN ISIDRO",
            "LA PLATA - VARELA (X BELGRANO)",
            "S.ISDRO (X B.AYRE X GAONA)",
            "S.ISDRO (X B.AYRE X HURLING)",
            "S.ISIDRO (X CAMARGO)",
            "S.ISIDRO-ALPARGATAS (X PASCO)",
            "S.ISIDRO-ALPARGATAS (X RUTA 4)",
            "VARELA - LA PLATA (X BELGRANO)"
        ]
    },
    406: {
        nombre: "406 [TALP]",
        ramales: [
            "06 HASTA RAMOS MEJÍA",
            "13 HACIA SAN JUSTO",
            "22 HACIA PZA. SAN JUSTO",
            "A LOMAS",
            "A PZA SAN JUSTO (METROBUS)",
            "HACIA LOMAS DE ZAMORA",
            "HACIA PZA. SAN JUSTO",
            "HACIA RAMOS MEJÍA",
            "HACIA SAN JOSÉ",
            "HACIA SAN JUSTO",
            "HASTA BURZACO",
            "HASTA LOMAS DE ZAMORA",
            "HASTA RAMOS MEJÍA",
            "HASTA SAN JOSÉ"
        ]
    },
    418: {
        nombre: "418",
        ramales: [
            "A BERAZATEGUI",
            "A LA PLATA (PZA MORENO)"
        ]
    },
    518: {
        nombre: "518",
        ramales: [
            "[SEMIRAP] HASTA B. AEROPUERTO",
            "[SEMIRAP] HASTA REP.NIÑOS"
        ]
    },
    520: {
        nombre: "520",
        ramales: [
            "[18] A ESTACION FFCC GRAL ROCA",
            "[18] A PARAJE HERMOSURA",
            "[18] A RUTA 11 Y 615",
            "[18] HERMOSURA -EST. FFCC ROCA",
            "[19] A ESTACION FFCC GRAL ROCA",
            "[19] A RUTA 11 Y 615",
            "[2] A ESTACION FFCC GRAL ROCA",
            "[2] A RUTA 11 Y 615"
        ]
    },
    ESTE: {
        nombre: "ESTE",
        ramales: [
            "14 DESDE CORREAS (HASTA1 Y 44)",
            "[11] A ESTACION FFCC GRAL ROCA",
            "[11] A ESTACION FFCC X B° UPCN",
            "[11] A RUTA 11 Y 615",
            "[11] A RUTA 11 Y 615 X B° UPCN",
            "[14] X AV. 13 A 122 Y 32",
            "[14] X AV.13 A 22 Y 659",
            "[14] X AV.13 A B. AROPUERTO",
            "[14] X AV.7 A 122 Y 32",
            "[14] X AV.7 A 22 Y 659",
            "[14] X AV.7 A P. SAN MARTIN",
            "[14] X AV.7 HASTA 1 Y 44",
            "[15]              A RUTA 11 Y 615",
            "[15] A ESTACION FFCC GRAL ROCA",
            "[15] A RUTA 11 Y 615",
            "[15] DE 117Y96 A ESTACION FFCC",
            "[15] DE P. MORENO A R.11 Y 615",
            "[16] A 122 Y 32",
            "[16] A RUTA 11 Y 615",
            "[16] HASTA 1 Y 44",
            "[45] IDA HASTA 122 Y 32",
            "[45] VUELTA HASTA 131Y76",
            "[46] IDA HASTA 122 Y 32",
            "[46] VUELTA HASTA 131Y76",
            "[61] A 13 Y 85",
            "[61] A ESTACION FFCC GRAL ROCA",
            "[80] A CORREAS",
            "[80] A ESTACION FFCC GRAL ROCA"
       ]
    },
    NORTE: {
        nombre: "NORTE",
        ramales: [
            "[.17] HASTA PLAZA ROCHA",
            "[10 XNACIONAL] A HERNANDEZ",
            "[10 XNACIONAL] HASTA AV.1 Y 49",
            "[10] A HERNANDEZ",
            "[10] HASTA PLAZA MORENO",
            "[11] A HERNANDEZ",
            "[11] HASTA PLAZA ROCHA",
            "[12] A BARRIO SAVOIA",
            "[12] HASTA PLAZA MORENO",
            "[13] A HERNANDEZ",
            "[13] HASTA ESTACION FFCC ROCA",
            "[15] A HERNANDEZ",
            "[15] HASTA AV.1 Y AV.60",
            "[16 X526] A HERNANDEZ",
            "[16 X526] HASTA AV.1 Y AV.60",
            "[16] A HERNANDEZ",
            "[16] HASTA AV.1 Y AV.60",
            "[17 XGORINA] A HERNANDEZ",
            "[17 XGORINA] A HERNANDEZ            ",
            "[17 XGORINA] HASTA AV.1 Y 49",
            "[17 XGORINA] HASTA P. ROCHA",
            "[17 XSAN JOSE] A HERNANDEZ",
            "[17 XSAN JOSE] HASTA AV.1 Y 49",
            "[17] A HERNANDEZ",
            "[17] HASTA PLAZA ROCHA",
            "[18] A HERNANDEZ",
            "[18] HASTA PLAZA ROCHA",
            "[RONDIN ESCUELA MAÑANA]",
            "[RONDIN ESCUELA MEDIODIA]",
            "[RONDIN ESCUELA TARDE]"
        ]
    },
    SUR: {
        nombre: "SUR",
        ramales: [
            "[10] A LOS HORNOS",        
            "[10] A T.OMNIBUS LA PLATA",
            "[19] A ESTACION FFCC GRAL ROCA",
            "[19] A PUENTE DE FIERRO",
            "[19] DE 14 Y 51 A P.DE FIERRO",
            "[19] HASTA DIAG.74 Y 22",
            "[19] HASTA PLAZA MORENO",
            "[21] A ESTACION FFCC GRAL ROCA",
            "[21] A PLAZA MORENO",
            "[21] A TERMINAL 273"
        ]
    },
    UNIVERSITARIO: {
        nombre: "UNIVERSITARIO",
        ramales: [
            "RONDIN HASTA 122 Y 52",
            "RONDIN HASTA 7 Y 49",
            "RONDIN 7 Y 49 X PERIODISMO",
            "RONDIN HASTA 122 Y 52",
            "RONDIN HASTA 7 Y 49"
        ]
    }
};

function obtenerLineas() {
    return Object.keys(lineasData).map(key => ({
        id: key,
        nombre: lineasData[key].nombre
    }));
}

function obtenerRamales(lineaId) {
    if (lineasData[lineaId]) {
        return lineasData[lineaId].ramales;
    }
    return [];
}